tap "homebrew/cask"

brew "awscli"
brew "direnv"
brew "jq"
brew "nodenv"
brew "ouchxp/nodenv/nodenv-nvmrc" # Not alphabetically sorted, but it's nodenv-related :-)
brew "nodenv/nodenv/nodenv-aliases"
brew "ruby-build"
brew "rbenv"
brew "redis"
brew "rust"
brew "ripgrep"
brew "tldr"
brew "tig"

cask "1password"
cask "cheatsheet"
cask "caffeine"
cask "docker"
cask "firefox"
cask "google-chrome"
cask "iterm2"
cask "keybase"
cask "rectangle"
cask "virtualbox"
cask "viscosity"
cask "visual-studio-code"
